spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: mid_redis_pw

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder:
                log_bind_parameter: true

  jackson:
    time-zone: Asia/Seoul

  graphql:
    path: /graphiql
    graphiql:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: your-very-long-random-secret-key
  exp:
    access: 1h
    refresh: 1d

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
