version: '3.9'
services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: bitnami_postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: mid
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local
