version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:16
    container_name: mid-postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRESQL_USERNAME=mid_user
      - POSTGRESQL_PASSWORD=mid_password
      - POSTGRESQL_DATABASE=mid
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/bitnami/postgresql
    restart: unless-stopped

  redis:
    image: bitnami/redis:7.2
    container_name: mid-redis
    environment:
      - TZ=Asia/Seoul
      - REDIS_PASSWORD=mid_redis_pw
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:
