spring:
  application:
    name: mid-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: localhost
      port: 6379
      password: redis

server:
  servlet:
    session:
      timeout: 30m

security:
  permit-all:
    - /api/auth/login
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /actuator/**

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
